# Generated by Django 5.2.6 on 2025-10-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_votocomentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='reportado',
            field=models.BooleanField(default=False),
        ),
    ]
