# Generated by Django 5.2.6 on 2025-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comentario_reportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
